name: Release radiance tool

on:
  push:
    branches: [ tx_meta ]
  pull_request:
    branches: [ main ]

# on:
#   push:
#     tags:
#       - v*

jobs:
  build:
    runs-on: [ubuntu-20.04]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup go env
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.7'
          check-latest: true

      - name: Cache rocksdb build
        uses: actions/cache@v3
        with:
          path: |
            ~/radiance-triton/facebook/
            ~/radiance-triton/radiance-triton/facebook/

      - name: build binaries
        run: |
            sudo cp /usr/bin/go /usr/bin/go1.19.7

            # snappy
            sudo apt update
            sudo apt-get install -y libsnappy-dev build-essential cmake zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

            # protoc
            go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
            export PATH="$PATH:$(go env GOPATH)/bin"
            wget https://github.com/protocolbuffers/protobuf/releases/download/v22.3/protoc-22.3-linux-x86_64.zip
            unzip protoc-22.3-linux-x86_64.zip
            sudo mv bin/protoc /usr/bin/protoc
            sudo chmod +x /usr/bin/protoc

            # deps
            make gen-proto

            # build
            make full

            ls -lha .


      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            radiance
